//
// Generated file, do not edit! Created by nedtool 4.6 from util/PPDU.msg.
//

#ifndef _PPDU_M_H_
#define _PPDU_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "IEEE802154Enum.h"
// }}

/**
 * Class generated from <tt>util/PPDU.msg:28</tt> by nedtool.
 * <pre>
 * packet pdDataInd
 * {
 *     unsigned char psduLength;       // ≤ aMaxPHYPacketSize
 *     unsigned char ppduLinkQuality;  // 0x00–0xff
 *     // PSDU Payload is just encapsulated
 * }
 * </pre>
 */
class pdDataInd : public ::cPacket
{
  protected:
    unsigned char psduLength_var;
    unsigned char ppduLinkQuality_var;

  private:
    void copy(const pdDataInd& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const pdDataInd&);

  public:
    pdDataInd(const char *name=NULL, int kind=0);
    pdDataInd(const pdDataInd& other);
    virtual ~pdDataInd();
    pdDataInd& operator=(const pdDataInd& other);
    virtual pdDataInd *dup() const {return new pdDataInd(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getPsduLength() const;
    virtual void setPsduLength(unsigned char psduLength);
    virtual unsigned char getPpduLinkQuality() const;
    virtual void setPpduLinkQuality(unsigned char ppduLinkQuality);
};

inline void doPacking(cCommBuffer *b, pdDataInd& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, pdDataInd& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>util/PPDU.msg:34</tt> by nedtool.
 * <pre>
 * packet ppdu
 * {
 *     unsigned char Preamble[4];      // Synchronization Header (SHR) 
 *     unsigned char SFD;              // Start of Frame Delimiter (8-bit except ASK)
 *     unsigned char PHR;              // PHY Header containing 7 Bits Frame Length & 1 Bit Reserved
 * }
 * </pre>
 */
class ppdu : public ::cPacket
{
  protected:
    unsigned char Preamble_var[4];
    unsigned char SFD_var;
    unsigned char PHR_var;

  private:
    void copy(const ppdu& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ppdu&);

  public:
    ppdu(const char *name=NULL, int kind=0);
    ppdu(const ppdu& other);
    virtual ~ppdu();
    ppdu& operator=(const ppdu& other);
    virtual ppdu *dup() const {return new ppdu(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPreambleArraySize() const;
    virtual unsigned char getPreamble(unsigned int k) const;
    virtual void setPreamble(unsigned int k, unsigned char Preamble);
    virtual unsigned char getSFD() const;
    virtual void setSFD(unsigned char SFD);
    virtual unsigned char getPHR() const;
    virtual void setPHR(unsigned char PHR);
};

inline void doPacking(cCommBuffer *b, ppdu& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ppdu& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>util/PPDU.msg:40</tt> by nedtool.
 * <pre>
 * message edConf
 * {
 *     unsigned char status @enum(phyState);  // compare IEEE802154Enum.h
 *     unsigned char EnergyLevel;             // 0x00–0xff
 * }
 * </pre>
 */
class edConf : public ::cMessage
{
  protected:
    unsigned char status_var;
    unsigned char EnergyLevel_var;

  private:
    void copy(const edConf& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const edConf&);

  public:
    edConf(const char *name=NULL, int kind=0);
    edConf(const edConf& other);
    virtual ~edConf();
    edConf& operator=(const edConf& other);
    virtual edConf *dup() const {return new edConf(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned char getStatus() const;
    virtual void setStatus(unsigned char status);
    virtual unsigned char getEnergyLevel() const;
    virtual void setEnergyLevel(unsigned char EnergyLevel);
};

inline void doPacking(cCommBuffer *b, edConf& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, edConf& obj) {obj.parsimUnpack(b);}


#endif // ifndef _PPDU_M_H_

